config/routes.rb
Rails.application.routes.draw do
  resources :dishes, only: [ :index, :new, :create ]
  resources :feeds, only: [ :index, :show, :new, :create ]

  resources :tags do
  end

  resources :goals do
    patch :update_status, on: :member
  end

  resources :links, except: :index do
    resources :comments, only: [ :create, :edit, :update, :destroy ]
  end

  get "/comments" => "comments#index"

  root "links#index"

  resources :sessions, only: [ :new, :create ] do
    delete :destroy, on: :collection
  end

  get "/logout", to: "sessions#destroy", as: "logout"

  resources :portfolio, only: [ :index ]

  resources :users, only: [ :new, :create, :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link

  validates :body, presence: true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
end

app/models/feed.rb
require "feedjira"
require "http"


class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy

  def fetch_and_parse
    rss_feed = Feedjira.parse(HTTP.get(url).to_s)

    update(
      title: rss_feed.title,
      #   description: rss_feed.description
    )

    rss_feed.entries.each do |entry|
      entries.find_or_create_by(url: entry.url) do |e|
        e.title = entry.title
        e.published_at = entry.published
        e.summary = entry.summary
      end
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  validates :title,
            presence: true,
            uniqueness: { case_sensitive: false }

  validates :url,
          format: { with: %r{\Ahttps?://} },
          allow_blank: true

  # Virtual attribute
  attr_accessor :tags_input

  # Callback to process tags after the link is saved
  after_save :assign_tags

  def comment_count
    comments.length
  end

  private

  def assign_tags
    return unless tags_input

    # Split the input by commas, strip whitespace, and find or create tags
    tag_names = tags_input.split(",").map(&:strip).uniq
    tags_to_assign = tag_names.map { |name| Tag.find_or_create_by(name: name) }

    tags_to_assign.each do |tag|
      Tagging.find_or_create_by(link: self, tag: tag)
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :links, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
    belongs_to :link
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :admin, inclusion: { in: [ true, false ] }

    validates :username,
            presence: true,
            length: { minimum: 3 },
            uniqueness: { case_sensitive: false }

    validates :password, length: { minimum: 8 }

    # Ensure email is unique
    validates :email, uniqueness: true

    has_many :links, dependent: :destroy
    has_many :comments
    has_many :goals

    def owns_link?(link)
        self.admin? || self == link.user
    end

    def owns_comment?(comment)
        self.admin? || self == comment.user
    end
    def admin?
        self.admin
    end
    def display
        self.admin? ? self.username + " [Admin]" : self.username
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
    before_action :prevent_unauthorized_user_access, only: [ :new ]

    def index
      # Entry.where("published_at > ?",   7.days.ago)
      @feeds = Feed.all
      if params[:time_filter] == "last_week"
        @time_filter = 7.days.ago
      elsif params[:time_filter] == "last_month"
        @time_filter = 31.days.ago
      else
        @time_filter = 365.days.ago
      end
      @last_published_at = Entry.maximum(:published_at)
    end

    def show
      @feed = Feed.find(params[:id])
      @entries = @feed.entries.order(published_at: :desc)
    end

    def new
      @feed = Feed.new
    end

    def create
      @feed = Feed.new(feed_params)
      if @feed.save
        @feed.fetch_and_parse
        redirect_to feeds_path, notice: "Feed added successfully!"
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def feed_params
      params.require(:feed).permit(:url)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def truncate_link(link, length = 50)
        link.length > length ? "#{link[0, length]}..." : link
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/resumeparser_helper.rb
module ResumeparserHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/index.html.erb
<div class="row">
<h1>Feeds</h1> 
<small>
Last article published at: <%= time_ago_in_words(@last_published_at) %> ago
</small>

</div>
<% if logged_in? %>
    <%= turbo_frame_tag "add_feed" do %>
        <%= link_to 'Add Feed', new_feed_path %>
    <% end %>
<% end %>


<br>
<%= link_to 'All', feeds_path, method: :get, class: 'filter-button' %>
<%= link_to 'Last Week', feeds_path(time_filter: "last_week"), method: :get, class: 'filter-button' %>
<%= link_to 'Last Month', feeds_path(time_filter: "last_month"), method: :get, class: 'filter-button' %>

<div class="cards">
<% @feeds.each do |feed| %>
    <% if feed.entries.where("published_at > ?", @time_filter).count > 0 %>
        <div class="card">
        <h2> <%= link_to feed.title || feed.url, feed_path(feed) %> </h2>

        <ul>
            <% feed.entries.where("published_at > ?", @time_filter).order(published_at: :desc).limit(20).each do |entry| %>
                <li>
                <a href="<%= entry.url %>" target="_blank"><%= entry.title %></a>
                </li>
            <% end %>
        </ul>
        </div>
    <% end %>
<% end %>
</div>

app/views/feeds/new.html.erb
<h1>Add a New Feed</h1>

<%= turbo_frame_tag "add_feed" do %>
  <%= form_with model: @feed, local: true, data: {turbo: false} do |form| %>
    <%= form.label :url %>
    <%= form.text_field :url %>
    <%= form.submit 'Add Feed' %>
  <% end %>
<% end %>

app/views/feeds/show.html.erb
<h1><%= @feed.title %></h1>
<div class="card">
<ul>
  <% @entries.each do |entry| %>
    <li>
      <a href="<%= entry.url %>" target="_blank"><%= entry.title %></a>
    </li>
  <% end %>
</ul>
</div>

app/views/tags/index.html.erb
<div class="tags">
    <% @tags.each do |tag| %>
        <span class="tag">
            <%= link_to tag.name, tag_path(tag)%> 
            <%= tag.taggings.count %>
        </span>
    <% end %>
</div>

app/views/tags/show.html.erb
Links tagged with tag: <span class="tag"><%= @tag.name %> </span>

<ul class="links">
    <% @tag.links.each do |link| %>
        <%= render partial: "links/link", locals: {link: link} %> 
    <% end %>
</ul>