config/routes.rb
Rails.application.routes.draw do
  resources :dishes, only: [ :index, :new, :create ]
  resources :feeds, only: [ :index, :show, :new, :create ]

  resources :tags do
  end

  resources :goals do
    patch :update_status, on: :member
  end

  resources :links, except: :index do
    resources :comments, only: [ :create, :edit, :update, :destroy ]
  end

  get "/comments" => "comments#index"

  root "links#index"

  resources :sessions, only: [ :new, :create ] do
    delete :destroy, on: :collection
  end

  get "/logout", to: "sessions#destroy", as: "logout"

  resources :portfolio, only: [ :index ]

  resources :users, only: [ :new, :create, :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link

  validates :body, presence: true
end

app/models/dish.rb
class Dish < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
end

app/models/feed.rb
require "feedjira"
require "http"


class Feed < ApplicationRecord
  has_many :entries, dependent: :destroy

  def fetch_and_parse
    rss_feed = Feedjira.parse(HTTP.get(url).to_s)

    update(
      title: rss_feed.title,
      #   description: rss_feed.description
    )

    rss_feed.entries.each do |entry|
      entries.find_or_create_by(url: entry.url) do |e|
        e.title = entry.title
        e.published_at = entry.published
        e.summary = entry.summary
      end
    end
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  validates :title,
            presence: true,
            uniqueness: { case_sensitive: false }

  validates :url,
          format: { with: %r{\Ahttps?://} },
          allow_blank: true

  # Virtual attribute
  attr_accessor :tags_input

  # Callback to process tags after the link is saved
  after_save :assign_tags

  def comment_count
    comments.length
  end

  private

  def assign_tags
    return unless tags_input

    # Split the input by commas, strip whitespace, and find or create tags
    tag_names = tags_input.split(",").map(&:strip).uniq
    tags_to_assign = tag_names.map { |name| Tag.find_or_create_by(name: name) }

    tags_to_assign.each do |tag|
      Tagging.find_or_create_by(link: self, tag: tag)
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :links, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
    belongs_to :link
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :admin, inclusion: { in: [ true, false ] }

    validates :username,
            presence: true,
            length: { minimum: 3 },
            uniqueness: { case_sensitive: false }

    validates :password, length: { minimum: 8 }

    # Ensure email is unique
    validates :email, uniqueness: true

    has_many :links, dependent: :destroy
    has_many :comments
    has_many :goals

    def owns_link?(link)
        self.admin? || self == link.user
    end

    def owns_comment?(comment)
        self.admin? || self == comment.user
    end
    def admin?
        self.admin
    end
    def display
        self.admin? ? self.username + " [Admin]" : self.username
    end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  # Display a list of all goals
  def index
    @goals = current_user.goals
    @end_dates = current_user.goals.distinct.pluck(:end_date)
  end


  # Handle form submission to create a new goal
  def create
    puts goal_params
    @goal = Goal.new(goal_params)
    if @goal.save
      redirect_to goals_path, notice: "Goal was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update_status
    @goal = Goal.find(params[:id])
    if @goal.update(status: "completed")
      # render json: { status: 'completed' }, status: :ok
      redirect_to goals_path
    else
      render json: { error: "Failed to update" }, status: :unprocessable_entity
    end
  end


  private

  # Strong parameters to whitelist the goal attributes
  def goal_params
    # Add user_id to params before permitting the other parameters
    params[:goal][:user_id] = current_user.id if current_user

    # Permit the parameters
    params.require(:goal).permit(:title, :goal_type, :end_date, :user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def truncate_link(link, length = 50)
        link.length > length ? "#{link[0, length]}..." : link
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/resumeparser_helper.rb
module ResumeparserHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<section class="cards">
    <div id="goals" class="card">
        <h3> Goals </h3>
        <ul>
            <li> Set clear goals </li>
            <li> Understand your why ? </li>
            <li> Track your progress </li>
        </ul>
    </div>
    <div id="discipline" class="card">
        <h3> Discipline </h3>
        <ul>
            <li> Build good habits </li>
            <li> Celebrate small wins </li>
            <li> Eliminate Distractions </li>
            <li> Physical Activities helps with mental focus</li>
        </ul>
    </div>

    <div id="attitude" class="card">
    <h3> Attitude </h3>
        <ul>
            <li> Stay disciplined </li>
            <li> Seek Accountability </li>
            <li> Embrace Setbacks </li>
        </ul>
    </div>

</section>

<% if current_user.username == "rgupta" %>
<h3> Milestones </h3>
<ul id="milestones">
    <li>🎉 Nov 21, 2023 - Finished 1000 LOC code running in production. </li>
</ul>
<section class="cards">

    <section class="card">
        <h3>Q. Why RoR?</h3>
        <ul>
            <li>Iterating on a website is faster. No compilation or build step. Easy testing and deployment.</li>
            <li>Underlying tech stack doesnt change. HTML, CSS, and JS still support features from the 1995 era.</li>
            <li>Website can be adapted to work on mobile devices using PWA and responsive design.</li>
            <li>Easier to build a side hustle while working on a job.</li>
            <li>Best for personal projects.</li>
        </ul>
    </section>

    <section class="card">
        <h3>Q. How can I learn it in 4 months, when other people take years to master it?</h3>
        <ul>
            <li>I will focus solely on learning RoR and nothing else. This means not learning Node.js, Rust, Flutter, app development, Python, ML, Golang, databases, Chrome extension, games, etc. A lot must be sacrificed to make real progress on RoR. Once comfortable with RoR, other things will come easier to me.</li>
            <li>I will be working on the same codebase consistently.</li>
            <li>The Motivator framework will help me stay focused on track.</li>
        </ul>
    </section>

    <section class="card">
        <h3>Q. What is your vision?</h3>
        <ul>
            <li>In 4 months, I will reach a stage where I understand the nuances of web development and go beyond building a simple blog/app in Rails. This includes PWA, SEO, latency, performance and throughput optimization, testing, chat/socket programming, and mail management. The focus is on breadth in the Rails domain.</li>
            <li>In the following 9 months, the goal is to build a product business with a team and secure some grant/venture funding.</li>
        </ul>
    </section>

    <section class="card">
        <h3>Q. How do you avoid getting bored from the learning process?</h3>
        <p>Because following a book or a single project can get monotonous, a multi-pronged approach to development will be used:</p>
        <ul>
            <li>Develop features as per the roadmap, making progress on my goals.</li>
            <li>Publish at least one blog post per week.</li>
            <li>Ask the community in the <a href="https://discuss.rubyonrails.org" target="_blank">Ruby on Rails forum</a>.</li>
            <li>Open some PRs in the Lobsters repository.</li>
            <li>Post YouTube/Twitch videos about Rails development.</li>
        </ul>
    </section>
</section>
<% end %>

<% if logged_in? %>
    <div id="goal-form">
        <%= form_for :goal, url: goals_path(@goal) do |f| %>
            <div class="form-group">
            <%= f.text_area :title, class: "form-control", placeholder: "Title", required: true %>
            </div>

            <div class="form-group">
            <%= f.select :goal_type, options_for_select([
                ["project", "project"], ["writing", "writing"], ["video", "video"], 
                ["open-source", "open-source"]]), {}, class: "form-select", required: true %>
            </div>

            <div class="form-group">
            <%= f.date_field :end_date, value: Date.today, class: "form-control", required: true %>
            </div>

            <div class="form-group">
            <%= f.button "Add Goal", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>
<% end %>

<div id="goals">
    <h3> Committed goals </h3>
    <div class="cards">
        <% @end_dates.sort.reverse.each do |end_date| %>
            <div class="card">
                <h4> <%=end_date %> </h4>
                <ul>
                    <% @goals.where(end_date: end_date).each do |goal| %>
                        <% if goal.status == "pending" %>
                        <li>
                            <%= link_to '✅', update_status_goal_path(goal), method: :patch, data: { turbo_method: :patch }, remote: true, class: "update-status" %>
                            <%= goal.title %>
                        </li>
                      
                        <% else %>
                            <li>  🎉 <%= goal.title %>   </li>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        <% end %>
    </div>
</div>